# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sets.l2norm <- function(v1, v2) {
    .Call('abSan_sets_l2norm_cpp', PACKAGE = 'abSan', v1, v2)
}

sets.nearest.vert <- function(pt, B) {
    .Call('abSan_sets_nearest_vert_cpp', PACKAGE = 'abSan', pt, B)
}

sets.inside.pt <- function(vPt, mG, vC) {
    .Call('abSan_sets_inside_pt_cpp', PACKAGE = 'abSan', vPt, mG, vC)
}

sets.inside.pts <- function(mPts, mG, vC) {
    .Call('abSan_sets_inside_pts_cpp', PACKAGE = 'abSan', mPts, mG, vC)
}

sets.inside.pts.idx <- function(mPts, mG, vC) {
    .Call('abSan_sets_inside_pts_idx_cpp', PACKAGE = 'abSan', mPts, mG, vC)
}

sets.nearest.line <- function(pt, mG, vC) {
    .Call('abSan_sets_nearest_line_cpp', PACKAGE = 'abSan', pt, mG, vC)
}

sets.Hausdorff.core <- function(mA, mZ, mG, vC) {
    .Call('abSan_sets_Hausdorrf_core_cpp', PACKAGE = 'abSan', mA, mZ, mG, vC)
}

sets.unique <- function(mZ, tol) {
    .Call('abSan_sets_unique_cpp', PACKAGE = 'abSan', mZ, tol)
}

sets.lineIntersect <- function(set, dir, intersect) {
    .Call('abSan_sets_lineIntersect_cpp', PACKAGE = 'abSan', set, dir, intersect)
}

sets.GCtoZ <- function(mG, vC) {
    .Call('abSan_sets_GCtoZ_cpp', PACKAGE = 'abSan', mG, vC)
}

sets.ZGtoC <- function(mZ, mG) {
    .Call('abSan_sets_ZGtoC_cpp', PACKAGE = 'abSan', mZ, mG)
}

sets.ZtoGC <- function(mZ) {
    .Call('abSan_sets_ZtoGC_cpp', PACKAGE = 'abSan', mZ)
}

sets.shape.preserve <- function(set, dTol) {
    .Call('abSan_sets_shape_preserve_cpp', PACKAGE = 'abSan', set, dTol)
}

abSan.C <- function(iA, set, vPun, model, print_output = TRUE, boCountFrom1 = TRUE) {
    .Call('abSan_abSan_C_cpp', PACKAGE = 'abSan', iA, set, vPun, model, print_output, boCountFrom1)
}

abSan.rComponent <- function(iA, set, vPun, model, print_output = TRUE, boCountFrom1 = TRUE) {
    .Call('abSan_abSan_rComponent_cpp', PACKAGE = 'abSan', iA, set, vPun, model, print_output, boCountFrom1)
}

abSan.rCore <- function(set, vPun, model, print_output = TRUE, boCountFrom1 = TRUE) {
    .Call('abSan_abSan_rCore', PACKAGE = 'abSan', set, vPun, model, print_output, boCountFrom1)
}

sets.bind <- function(lA) {
    .Call('abSan_bind_par_cpp', PACKAGE = 'abSan', lA)
}

